version: "3.9"

services:
    db:
        container_name: pockly-db
        image: postgres:14-alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - pgdata:/var/lib/postgresql/data/pgdata

volumes:
    pgdata:
