name: Build and lint

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

env:
    DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
    CI: true
jobs:
    Lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: yarn
                  cache-dependency-path: ./yarn.lock

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            # - name: Generate types
            #   run: yarn generate

            - name: Check formatting
              run: yarn format:check

            - name: Typecheck
              run: yarn typecheck

            - name: Lint
              run: yarn lint

    Build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: yarn
                  cache-dependency-path: ./yarn.lock

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            # - name: Generate types
            #   run: yarn generate

            - name: Build project
              run: yarn build
